/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.bookingController;
import Model.BookingJadwal;
import Model.loginSession;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FACHRUDDIN GHALIBI
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form menuAdmin
     */
    private DefaultTableModel modelTableBooking;
    private bookingController bkgCtrl;
    public MenuAdmin() {
        
        initComponents();
        bkgCtrl = new bookingController();
        String[] judulTabel = {"id", "namaPasien", "waktuBooking", "tanggalBooking", "namaDokter", "status"};
        modelTableBooking = new DefaultTableModel(judulTabel, 0);
        tabelbooking.setModel(modelTableBooking);
        loadDataBooking();
    }
    public void loadDataBooking(){
        List<BookingJadwal> dataBooking = bkgCtrl.getAllBookingJadwal();
        for (BookingJadwal data:dataBooking){
            Object[] rowData = {
            data.getId_booking(), 
            data.getNamaPasien(),
            data.getWaktuBooking(),
            data.getTanggalBooking(),
            data.getNamaDokter(),
            data.getStatus()
            };
            modelTableBooking.addRow(rowData);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelbooking = new javax.swing.JTable();
        refreshAdmin = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Menu Admin");

        tabelbooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelbooking.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelbookingAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabelbooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbookingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelbooking);

        refreshAdmin.setText("Refresh");
        refreshAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshAdminActionPerformed(evt);
            }
        });

        logoutbtn.setText("Logout");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(refreshAdmin)
                            .addComponent(logoutbtn))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(refreshAdmin)
                        .addGap(28, 28, 28)
                        .addComponent(logoutbtn)))
                .addContainerGap(300, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelbookingAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelbookingAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelbookingAncestorAdded

    private void tabelbookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbookingMouseClicked
        int selectedRow = tabelbooking.getSelectedRow();
        if (selectedRow != -1) {
            int id_Booking = (int) modelTableBooking.getValueAt(selectedRow, 0);
            String namaPasien = modelTableBooking.getValueAt(selectedRow, 1).toString();
            String waktuBooking = modelTableBooking.getValueAt(selectedRow, 2).toString();
            String tanggalBooking = modelTableBooking.getValueAt(selectedRow, 3).toString();
            String namaDokter = modelTableBooking.getValueAt(selectedRow, 4).toString();
            String status = modelTableBooking.getValueAt(selectedRow, 5).toString();
            
            detailBooking databooking = new detailBooking();
            databooking.detailBooking(id_Booking, namaPasien, waktuBooking, tanggalBooking, namaDokter, status);
            databooking.setVisible(true);
            

        }
    }//GEN-LAST:event_tabelbookingMouseClicked

    private void refreshAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshAdminActionPerformed
        tabelbooking.removeAll();
        int rows = modelTableBooking.getRowCount();
        for (int i = rows - 1; i >= 0; i--){
            modelTableBooking.removeRow(i);
        }
        loadDataBooking();
    }//GEN-LAST:event_refreshAdminActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin logout?", "Konfirmasi Logout",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    
    if (response == JOptionPane.YES_OPTION) {
        loginSession.clearSession();

        Login loginWindow = new Login();
        loginWindow.setVisible(true);

        this.dispose();
    }
    }//GEN-LAST:event_logoutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton refreshAdmin;
    private javax.swing.JTable tabelbooking;
    // End of variables declaration//GEN-END:variables
}
